// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNLGm-xj1AdRiQ4N9w7H8L3bvetkRO_GQ',
    appId: '1:920997739613:web:1fec5ccfa05818c80061b4',
    messagingSenderId: '920997739613',
    projectId: 'resonate-audio-sync',
    authDomain: 'resonate-audio-sync.firebaseapp.com',
    storageBucket: 'resonate-audio-sync.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADyfDR0F534MQML6E2-jGOodxuZUNtaWE',
    appId: '1:920997739613:android:70dd692ac81b4dbb0061b4',
    messagingSenderId: '920997739613',
    projectId: 'resonate-audio-sync',
    storageBucket: 'resonate-audio-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrebMWpljyL0OLHLMZkIcFifJG_UISCos',
    appId: '1:920997739613:ios:dadb3caeb2f549150061b4',
    messagingSenderId: '920997739613',
    projectId: 'resonate-audio-sync',
    storageBucket: 'resonate-audio-sync.firebasestorage.app',
    iosBundleId: 'com.example.resonateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrebMWpljyL0OLHLMZkIcFifJG_UISCos',
    appId: '1:920997739613:ios:dadb3caeb2f549150061b4',
    messagingSenderId: '920997739613',
    projectId: 'resonate-audio-sync',
    storageBucket: 'resonate-audio-sync.firebasestorage.app',
    iosBundleId: 'com.example.resonateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNLGm-xj1AdRiQ4N9w7H8L3bvetkRO_GQ',
    appId: '1:920997739613:web:3e14a55871b398910061b4',
    messagingSenderId: '920997739613',
    projectId: 'resonate-audio-sync',
    authDomain: 'resonate-audio-sync.firebaseapp.com',
    storageBucket: 'resonate-audio-sync.firebasestorage.app',
  );
}
